### ISSUE TITLE
If player have over 21

### ISSUE THREAD

**Issue by Elmona** [Elmona/Blackjack#10]
The game should automagiskt end!

**Comment by Elmona** [comment]
And the dealer should not draw any more cards

**Comment by Elmona** [comment]
https://github.com/Elmona/Blackjack/commit/ce57fa9237df6246fefcec450a9cfb4c9f8e1833

What do you guys think?

**Comment by Marrieto** [comment]
Seems to be working for me! Maybe we can close this issue?
