### ISSUE TITLE
New win game rule

### ISSUE THREAD

**Issue by Marrieto** [Elmona/Blackjack#3]
Design and implement a variable rule for who wins the game. This variation could, for example, change who wins on an equal score (in one implementation the Dealer wins, in the other the Player). The design should make it easy to add other variants without changing the Dealer. Use the same design pattern as used in the Soft 17 design.

**Comment by simonnice** [comment]
Should be resolved in rules branch, ples take a look and give opinion, kay?

**Comment by Elmona** [comment]
Well done!
