### ISSUE TITLE
Make parent class for the new game rules, remove duplication

### ISSUE THREAD

**Issue by Marrieto** [Elmona/Blackjack#4]
The code for getting a card from the deck, show the card and give it to a player is duplicated in a number of places. Make a refactoring to remove this duplication and that supports low coupling/high cohesion (i.e. check how you can evaluate different solutions to the problem and select the one that gives the best result according to low coupling/high cohesion). The code that is duplicated is similar to this:
Card c = deck.GetCard();
c.Show(true/false)
player.DealCard(c);

**Comment by Elmona** [comment]
I think we need to take a look at this!

**Comment by Elmona** [comment]
Maybe two abstract classes, one in INewStrategy game that take two arguments. player/dealer and if card is shown.

And maybe someting similar with player/dealer classes

**Comment by Elmona** [comment]
https://github.com/Elmona/Blackjack/commit/e218dd450fefaf5e5ec5bd5f529a65aef73165c0

Take a look at this commit guys.. I think it works as expected!

**Comment by Elmona** [comment]
There is still 2 duplications in like dealer or something buuut

**Comment by Marrieto** [comment]
Can't find those duplicates?

**Comment by Elmona** [comment]
https://github.com/Elmona/Blackjack/blob/master/model/Dealer.cs#L45
https://github.com/Elmona/Blackjack/blob/master/model/Dealer.cs#L94

**Comment by Marrieto** [comment]
Nice, should be an easy fix by adding a private member function on player that does these three things!
