### ISSUE TITLE
Implement Observer pattern between

### ISSUE THREAD

**Issue by Marrieto** [Elmona/Blackjack#5]
Use the Observer-pattern to send an event to the user interface that a player (human or dealer) has got a new card in his hand. When the event is handled the user interface should be redrawn to show the new hand (with the new card) and the game should be briefly paused, to make the game a bit more exciting, the pausing code should be in the user interface (view or controller) and not in the model. The pause should be when any player (dealer or human) gets a card.
For example, when starting the game the following “pattern” of pauses should present in the user interface:

Dealer:
Player: c1 (player gets the first card)
*pause*
Dealer: c1 (dealer gets the first card)
Player: c1
*pause*
Dealer: c1
Player: c1, c2 (player gets the second card)
*pause*
Dealer: c1, c2 (dealer gets the second card)
Player: c1, c2

**Comment by Elmona** [comment]
Well, I think the observer pattern works kinda nice now. What do you guys say?

**Comment by Marrieto** [comment]
Yeah seems to work as intended
